apiVersion: v1
kind: ServiceAccount
metadata:
  name: scylla-readiness-validator
  labels:
    {{- include "scylla-readiness-check.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scylla-readiness-validator
  labels:
    {{- include "scylla-readiness-check.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "events"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scylla-readiness-validator
  labels:
    {{- include "scylla-readiness-check.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scylla-readiness-validator
subjects:
  - kind: ServiceAccount
    name: scylla-readiness-validator
    namespace: {{ .Release.Namespace }}
